// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectAPI.Models;

namespace projectAPI.Migrations
{
    [DbContext(typeof(VipContext))]
    [Migration("20190628092753_changeType")]
    partial class changeType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projectAPI.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusNumber")
                        .IsRequired();

                    b.Property<string>("BusType");

                    b.Property<int>("Capacity");

                    b.Property<DateTime>("RegistrationYear");

                    b.HasKey("Id");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("projectAPI.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BusId");

                    b.Property<DateTime>("Dob");

                    b.Property<string>("FirstMidName");

                    b.Property<string>("LastName");

                    b.Property<string>("License");

                    b.Property<int>("Performance");

                    b.Property<int>("Phone");

                    b.Property<string>("Picture");

                    b.Property<int>("Salary");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("projectAPI.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BusId");

                    b.Property<int>("MaintenanceCost");

                    b.Property<DateTime>("MaintenanceDate");

                    b.Property<string>("MaintenanceType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("projectAPI.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountPaid");

                    b.Property<int?>("DriverId");

                    b.Property<bool>("PayStatus");

                    b.Property<DateTime>("PaymentDate");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Salary");
                });

            modelBuilder.Entity("projectAPI.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int?>("BusId");

                    b.Property<string>("Busnum");

                    b.Property<int>("Cost");

                    b.Property<int?>("DriverId");

                    b.Property<string>("Drivername");

                    b.Property<int>("Passengers");

                    b.Property<DateTime>("SaleDate");

                    b.Property<int?>("TripId");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TripId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("projectAPI.Models.Trips", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusId");

                    b.Property<int>("DriverId");

                    b.Property<bool>("IsStandby");

                    b.Property<string>("Trip");

                    b.Property<DateTime>("TripDate");

                    b.Property<int>("TripMaintenanceCost");

                    b.Property<string>("TripMaintenanceType");

                    b.Property<int>("TripProfit");

                    b.Property<int>("TripSales");

                    b.Property<int>("TripWeek");

                    b.Property<int>("Waybill");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("projectAPI.Models.Driver", b =>
                {
                    b.HasOne("projectAPI.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId");
                });

            modelBuilder.Entity("projectAPI.Models.Maintenance", b =>
                {
                    b.HasOne("projectAPI.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId");
                });

            modelBuilder.Entity("projectAPI.Models.Salary", b =>
                {
                    b.HasOne("projectAPI.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");
                });

            modelBuilder.Entity("projectAPI.Models.Sales", b =>
                {
                    b.HasOne("projectAPI.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId");

                    b.HasOne("projectAPI.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("projectAPI.Models.Trips", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId");
                });

            modelBuilder.Entity("projectAPI.Models.Trips", b =>
                {
                    b.HasOne("projectAPI.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("projectAPI.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
